{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wazuh-k8s-hardening.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh-k8s-hardening.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "wazuh-k8s-hardening.selectorLabels" . | nindent 6 }}
{{- end }}
