{{- if and (not .Values.manager.existingSecret) .Values.manager.registrationPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh-k8s-hardening.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh-k8s-hardening.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  registration-password: {{ .Values.manager.registrationPassword | b64enc | quote }}
{{- end }}
